config/routes.rb
RailsMongoLogger::Engine.routes.draw do
  # Exception Logger
  resources :logged_exceptions do
    collection do
      post :clear
      post :query
      post :destroy_all
      get :feed
    end
  end

  root :to => 'logged_exceptions#index'
end

app/models/rails_exception_logger/logged_exception.rb
module RailsExceptionLogger
  class LoggedException
    include Mongoid::Document

    field :exception_class, type: String
    field :controller_name, type: String
    field :action_name, type: String
    field :message, type: Text
    field :backtrace, type: Text
    field :environment, type: Text
    field :request, type: Text
     field :created_at, type: DateTime

    HOSTNAME = `hostname -s`.chomp
    class << self
      def create_from_exception(controller, exception, data)
        message = exception.message.inspect
        message << "\n* Extra Data\n\n#{data}" unless data.blank?
        e = create! \
          :exception_class => exception.class.name,
          :controller_name => controller.controller_path,
          :action_name     => controller.action_name,
          :message         => message,
          :backtrace       => exception.backtrace,
          :request         => controller.request
      end

      def host_name
        HOSTNAME
      end
    end

    scope :by_exception_class, lambda {|exception_class| where(:exception_class => exception_class)}
    scope :by_controller_and_action, lambda {|controller_name, action_name| where(:controller_name => controller_name, :action_name => action_name)}
    scope :by_controller, lambda {|controller_name| where(:controller_name => controller_name)}
    scope :by_action, lambda {|action_name| where(:action_name => action_name)}
    scope :message_like, lambda {|query|  where('message like ?', "%#{query}%")}
    scope :days_old, lambda {|day_number| where('created_at >= ?', day_number.to_f.days.ago.utc)}
    scope :sorted, lambda { order('created_at DESC') }

    def name
      "#{self.exception_class} in #{self.controller_action}"
    end

    def backtrace=(trace)
      trace = sanitize_backtrace(trace) * "\n" unless trace.is_a?(String)
      write_attribute :backtrace, trace
    end

    def request=(request)
      if request.is_a?(String)
        write_attribute :request, request
      else
        max = request.env.keys.max { |a,b| a.length <=> b.length }
        env = request.env.keys.sort.inject [] do |env, key|
          env << '* ' + ("%-*s: %s" % [max.length, key, request.env[key].to_s.strip])
        end
        write_attribute(:environment, (env << "* Process: #{$$}" << "* Server : #{self.class.host_name}") * "\n")

        write_attribute(:request, [
            "* URL:#{" #{request.method.to_s.upcase}" unless request.get?} #{request.protocol}#{request.env["HTTP_HOST"]}#{request.fullpath}",
            "* Format: #{request.format.to_s}",
            "* Parameters: #{request.parameters.inspect}",
            "* Rails Root: #{rails_root}"
          ] * "\n")
      end
    end

    def controller_action
      @controller_action ||= "#{controller_name.camelcase}/#{action_name}"
    end

    def self.class_names
      select("DISTINCT exception_class").order(:exception_class).collect(&:exception_class)
    end

    def self.controller_actions
      select("DISTINCT controller_name, action_name").order(:controller_name,:action_name).collect(&:controller_action)
    end

    private
    @@rails_root      = Pathname.new(Rails.root).cleanpath.to_s
    @@backtrace_regex = /^#{Regexp.escape(@@rails_root)}/

    def sanitize_backtrace(trace)
      trace.collect { |line| Pathname.new(line.gsub(@@backtrace_regex, "[RAILS_ROOT]")).cleanpath.to_s }
    end

    def rails_root
      @@rails_root
    end
  end
end

app/models/rails_mongo_logger/logged_exception.rb
module RailsMongoLogger
  class LoggedException
    include Mongoid::Document
    include Mongoid::Timestamps::Created

    field :exception_class, type: String
    field :controller_name, type: String
    field :action_name, type: String
    field :message, type: String
    field :backtrace, type: String
    field :environment, type: String
    field :request, type: String
    field :created_at, type: DateTime

    HOSTNAME = `hostname -s`.chomp
    class << self
      def create_from_exception(controller, exception, data)
        message = exception.message.inspect
        message << "\n* Extra Data\n\n#{data}" unless data.blank?
        e = create! \
          :exception_class => exception.class.name,
          :controller_name => controller.controller_path,
          :action_name     => controller.action_name,
          :message         => message,
          :backtrace       => exception.backtrace,
          :request         => controller.request
      end

      def host_name
        HOSTNAME
      end
    end

    scope :by_exception_class, lambda {|exception_class| where(:exception_class => exception_class)}
    scope :by_controller_and_action, lambda {|controller_name, action_name| where(:controller_name => controller_name, :action_name => action_name)}
    scope :by_controller, lambda {|controller_name| where(:controller_name => controller_name)}
    scope :by_action, lambda {|action_name| where(:action_name => action_name)}
    scope :message_like, lambda {|query|  where('message like ?', "%#{query}%")}
    scope :days_old, lambda {|day_number| where('created_at >= ?', day_number.to_f.days.ago.utc)}
    scope :sorted, lambda { order('created_at DESC') }

    def name
      "#{self.exception_class} in #{self.controller_action}"
    end

    def backtrace=(trace)
      trace = sanitize_backtrace(trace) * "\n" unless trace.is_a?(String)
      write_attribute :backtrace, trace
    end

    def request=(request)
      if request.is_a?(String)
        write_attribute :request, request
      else
        max = request.env.keys.max { |a,b| a.length <=> b.length }
        env = request.env.keys.sort.inject [] do |env, key|
          env << '* ' + ("%-*s: %s" % [max.length, key, request.env[key].to_s.strip])
        end
        write_attribute(:environment, (env << "* Process: #{$$}" << "* Server : #{self.class.host_name}") * "\n")

        write_attribute(:request, [
            "* URL:#{" #{request.method.to_s.upcase}" unless request.get?} #{request.protocol}#{request.env["HTTP_HOST"]}#{request.fullpath}",
            "* Format: #{request.format.to_s}",
            "* Parameters: #{request.parameters.inspect}",
            "* Rails Root: #{rails_root}"
          ] * "\n")
      end
    end

    def controller_action
      @controller_action ||= "#{controller_name.camelcase}/#{action_name}"
    end

    def self.class_names
      order(:exception_class).collect(&:exception_class).uniq
    end

    def self.controller_actions
     #order(:controller_name, :action_name).collect(&:controller_action).uniq
     order(:controller_name).collect(&:controller_action).uniq
    end

    private
    @@rails_root      = Pathname.new(Rails.root).cleanpath.to_s
    @@backtrace_regex = /^#{Regexp.escape(@@rails_root)}/

    def sanitize_backtrace(trace)
      trace.collect { |line| Pathname.new(line.gsub(@@backtrace_regex, "[RAILS_ROOT]")).cleanpath.to_s }
    end

    def rails_root
      @@rails_root
    end

    def self.order(type)
      super("#{type} asc")
    end

  end
end

app/controllers/rails_exception_logger/logged_exceptions_controller.rb
module RailsExceptionLogger
  class LoggedExceptionsController < ApplicationController
    layout 'rails_exception_logger/application'

    cattr_accessor :application_name

    helper_method :params_filters

    #ApplicationController.class_eval do
    #  rescue_from Exception, :with => :log_exception_handler
    #end

    def index
      @exception_names    = LoggedException.class_names
      @controller_actions = LoggedException.controller_actions
      query
    end

    def query
      exceptions = LoggedException.sorted
      unless params[:id].blank?
        exceptions = exceptions.where(:id => params[:id])
      end
      unless params[:query].blank?
        exceptions = exceptions.message_like(params[:query])
      end
      unless params[:date_ranges_filter].blank?
        exceptions = exceptions.days_old(params[:date_ranges_filter])
      end
      unless params[:exception_names_filter].blank?
        exceptions = exceptions.by_exception_class(params[:exception_names_filter])
      end
      unless params[:controller_actions_filter].blank?
        c_a_params = params[:controller_actions_filter].split('/')
        controller_filter = c_a_params.first.underscore
        action_filter = c_a_params.last.downcase
        exceptions = exceptions.by_controller(controller_filter)
        exceptions = exceptions.by_action(action_filter)
      end
      @exceptions = exceptions.paginate(:page => params[:page], :per_page => 30)

      respond_to do |format|
        format.html { redirect_to :action => 'index' unless action_name == 'index' }
        format.js
      end
    end

    def feed
      @exceptions = LoggedException.all

      respond_to do |format|
        format.rss { render :layout => false }
      end
    end

    def show
      @exception = LoggedException.where(:id => params[:id]).first

      respond_to do |format|
        format.js
        format.html
      end
    end

    def destroy
      @exception = LoggedException.where(:id => params[:id]).first
      @exception.destroy
    end

    def destroy_all
      LoggedException.delete_all(:id => params[:ids]) unless params[:ids].blank?
      query
    end

    def clear
      LoggedException.delete_all
      redirect_to :back
    end

    private

    def params_filters
      {
        :query => params[:query],
        :date_ranges_filter => params[:date_ranges_filter],
        :exception_names_filter => params[:exception_names_filter],
        :controller_actions_filter => params[:controller_actions_filter],
      }
    end

    def access_denied_with_basic_auth
      headers["Status"]           = "Unauthorized"
      headers["WWW-Authenticate"] = %(Basic realm="Web Password")
      render :text => "Could't authenticate you", :status => '401 Unauthorized'
    end

    @@http_auth_headers = %w(X-HTTP_AUTHORIZATION HTTP_AUTHORIZATION Authorization)
    # gets BASIC auth info
    def get_auth_data
      auth_key  = @@http_auth_headers.detect { |h| request.env.has_key?(h) }
      auth_data = request.env[auth_key].to_s.split unless auth_key.blank?
      return auth_data && auth_data[0] == 'Basic' ? Base64.decode64(auth_data[1]).split(':')[0..1] : [nil, nil]
    end
  end
end

app/controllers/rails_mongo_logger/application_controller.rb
module RailsMongoLogger
  class ApplicationController < ActionController::Base
  end
end

app/controllers/rails_mongo_logger/logged_exceptions_controller.rb
module RailsMongoLogger
  class LoggedExceptionsController < ApplicationController
    layout 'rails_mongo_logger/application'

    cattr_accessor :application_name

    helper_method :params_filters

    #ApplicationController.class_eval do
    #  rescue_from Exception, :with => :log_exception_handler
    #end

    def index
      @exception_names    = LoggedException.class_names
      @controller_actions = LoggedException.controller_actions
      query
    end

    def query
      exceptions = LoggedException.sorted
      unless params[:id].blank?
        exceptions = exceptions.where(:id => params[:id])
      end
      unless params[:query].blank?
        exceptions = exceptions.message_like(params[:query])
      end
      unless params[:date_ranges_filter].blank?
        exceptions = exceptions.days_old(params[:date_ranges_filter])
      end
      unless params[:exception_names_filter].blank?
        exceptions = exceptions.by_exception_class(params[:exception_names_filter])
      end
      unless params[:controller_actions_filter].blank?
        c_a_params = params[:controller_actions_filter].split('/')
        controller_filter = c_a_params.first.underscore
        action_filter = c_a_params.last.downcase
        exceptions = exceptions.by_controller(controller_filter)
        exceptions = exceptions.by_action(action_filter)
      end
      @exceptions = exceptions.paginate(:page => params[:page], :per_page => 30)

      respond_to do |format|
        format.html { redirect_to :action => 'index' unless action_name == 'index' }
        format.js
      end
    end

    def feed
      @exceptions = LoggedException.all

      respond_to do |format|
        format.rss { render :layout => false }
      end
    end

    def show
      @exception = LoggedException.where(:id => params[:id]).first

      respond_to do |format|
        format.js
        format.html
      end
    end

    def destroy
      @exception = LoggedException.where(:id => params[:id]).first
      @exception.destroy
    end

    def destroy_all
      LoggedException.delete_all(:id => params[:ids]) unless params[:ids].blank?
      query
    end

    def clear
      LoggedException.delete_all
      redirect_to :back
    end

    private

    def params_filters
      {
        :query => params[:query],
        :date_ranges_filter => params[:date_ranges_filter],
        :exception_names_filter => params[:exception_names_filter],
        :controller_actions_filter => params[:controller_actions_filter],
      }
    end

    def access_denied_with_basic_auth
      headers["Status"]           = "Unauthorized"
      headers["WWW-Authenticate"] = %(Basic realm="Web Password")
      render :text => "Could't authenticate you", :status => '401 Unauthorized'
    end

    @@http_auth_headers = %w(X-HTTP_AUTHORIZATION HTTP_AUTHORIZATION Authorization)
    # gets BASIC auth info
    def get_auth_data
      auth_key  = @@http_auth_headers.detect { |h| request.env.has_key?(h) }
      auth_data = request.env[auth_key].to_s.split unless auth_key.blank?
      return auth_data && auth_data[0] == 'Basic' ? Base64.decode64(auth_data[1]).split(':')[0..1] : [nil, nil]
    end
  end
end

app/helpers/rails_exception_logger/logged_exceptions_helper.rb
module RailsExceptionLogger
  module LoggedExceptionsHelper

    def pretty_exception_date(exception)
      if Date.today == exception.created_at.to_date
        if false # exception.created_at > Time.now - 4.hours
          "#{time_ago_in_words(exception.created_at).gsub(/about /,"~ ")} agox"
        else
          "Today, #{exception.created_at.strftime(Time::DATE_FORMATS[:exc_time])}"
        end
      else
        exception.created_at.strftime(Time::DATE_FORMATS[:exc_date])
      end
    end

    def filtered?
      [:query, :date_ranges_filter, :exception_names_filter, :controller_actions_filter].any? { |p| params[p] }
    end

    def listify(text)
      list_items = text.scan(/^\s*\* (.+)/).map {|match| content_tag(:li, match.first) }
      content_tag(:ul, list_items)
    end

    def page_title(text)
      title = ""
      unless controller.application_name.blank?
        title << "#{controller.application_name} :: "
      end
      title << text.to_s
      content_for(:title, title.to_s)
    end

    # Rescue textilize call if RedCloth is not available.
    def pretty_format(text)
      begin
        textilize(text).html_safe
      rescue
        simple_format(text).html_safe
      end
    end


  end
 end

app/helpers/rails_mongo_logger/application_helper.rb
module RailsMongoLogger
  module ApplicationHelper


  end
end

app/helpers/rails_mongo_logger/logged_exceptions_helper.rb
module RailsMongoLogger
  module LoggedExceptionsHelper

    def pretty_exception_date(exception)
      if Date.today == exception.try(:created_at).try(:to_date)
        if false # exception.created_at > Time.now - 4.hours
          "#{time_ago_in_words(exception.created_at).gsub(/about /,"~ ")} agox"
        else
          "Today, #{exception.created_at.strftime(Time::DATE_FORMATS[:exc_time]) rescue nil}"
        end
      else
        exception.created_at.strftime(Time::DATE_FORMATS[:exc_date]) rescue nil
      end
    end

    def filtered?
      [:query, :date_ranges_filter, :exception_names_filter, :controller_actions_filter].any? { |p| params[p] }
    end

    def listify(text)
      list_items = text.scan(/^\s*\* (.+)/).map {|match| content_tag(:li, match.first) }
      content_tag(:ul, list_items)
    end

    def page_title(text)
      title = ""
      unless controller.application_name.blank?
        title << "#{controller.application_name} :: "
      end
      title << text.to_s
      content_for(:title, title.to_s)
    end

    # Rescue textilize call if RedCloth is not available.
    def pretty_format(text)
      begin
        textilize(text).html_safe
      rescue
        simple_format(text).html_safe
      end
    end


  end
 end

app/views/rails_mongo_logger/logged_exceptions/_exceptions.html.erb
<div id="exceptions">
  <div class="pages">
    <%= link_to('Clear History', {:action => :clear}, :confirm => "are you sure?", :method => :post) %>
    <%= link_to 'Delete Visible', { :action => 'destroy_all' }.merge(params_filters), :class => 'delete_visible_link' %>
    <strong><%= will_paginate @exceptions, :params => { :controller => "logged_exceptions", :action => "index" }.merge(params_filters), :style => 'display:inline' %></strong>
  </div>
  <h1>Exceptions <%= raw "<span>(filtered)</span>" if filtered? %> </h1>
  <table>
    <thead>
      <tr>
        <th>Exception</th>
        <th>Date</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @exceptions.each do |exception| %>
        <tr id="<%= dom_id(exception) %>" class="<%= cycle("eor", "") %> exception">
          <td>
            <div class="expclass"><%= link_to exception.name, {:action => "show", :id => exception}, :class => 'show_link' %></div>
            <span class="message"><%= h exception.message %></span>
          </td>
          <td class="time"><%= pretty_exception_date(exception) %></td>
          <td><%= link_to 'Delete', { :action => 'destroy', :id => exception }, :class => "util delete_link" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
   <div class="pages pages-bottom">
     <strong><%= will_paginate @exceptions, :params => { :controller => "logged_exceptions", :action => "index" }.merge(params_filters), :style => 'display:inline' %></strong>
   </div>
</div> <!-- #exceptions -->

app/views/rails_mongo_logger/logged_exceptions/_feed.html.erb
<ul id="feed" class="filters">
  <li><%= link_to "RSS Feed", feed_logged_exceptions_url(:format => :rss) %></li>
</ul>

app/views/rails_mongo_logger/logged_exceptions/_show.html.erb
<div class="tools">
  <%= link_to 'Delete', { :action => 'destroy', :id => @exception }, :class => "util delete_link" %>
  <span class="pipe">|</span>
  <%= link_to "Close", "#", :class => "util close_link" %>
</div>

<div class="date">
  <%= @exception.created_at.strftime(Time::DATE_FORMATS[:exc_full]) rescue nil %>
</div>
<h1><%= @exception.name %></h1>

<h2>Request</h2>
<%= pretty_format(@exception.request) %>

<h2>Backtrace</h2>
<%= simple_format @exception.message %>

<div id="backtrace">
  <%= raw @exception.backtrace.gsub(/\n/,"<br />") %>
</div>

<h2>Environment</h2>
<%= pretty_format(@exception.environment) %>

app/views/rails_mongo_logger/logged_exceptions/destroy.js.erb
$('#<%= dom_id(@exception) %>').addClass('deleted');
$('#showpage').hide();

app/views/rails_mongo_logger/logged_exceptions/destroy_all.js.erb
$('#exceptions').html('<%= escape_javascript render :partial => "exceptions" %>');
$('#showpage').hide();

app/views/rails_mongo_logger/logged_exceptions/index.html.erb
<% page_title t(".title") %>
<div id="right">
  <h3><%=t(".filters")%></h3>
  <ul id="all_exceptions" class="filters">
    <li><%= link_to t(".latest_exceptions"), :action => 'index', :id => nil %></li>
  </ul>
  <h4><%=t(".exception")%></h4>
  <ul id="exception_names" class="filters">
    <% @exception_names.each do |name| %>
      <li><%= link_to name, {:action => 'query', :exception_names_filter => "#{name}"}, :class => 'filter_link' %></li>
    <% end %>
  </ul>
  <h4><%=t(".controller_action")%></h4>
  <ul id="controller_actions" class="filters">
    <% @controller_actions.each do |action| %>
      <li><%= link_to action, {:action => 'query', :controller_actions_filter => "#{action}"}, :class => 'filter_link' %></li>
    <% end %>
  </ul>
  <h4><%=t(".dates")%></h4>
  <ul id="date_ranges" class="filters">
    <li><%= link_to t(".today"), {:action => 'query', :date_ranges_filter => "1"}, :title => "1", :class => 'filter_link' %></li>
    <li><%= link_to t(".last_few_days"), {:action => 'query', :date_ranges_filter => "3"}, :title => "3", :class => 'filter_link' %></li>
    <li><%= link_to t(".last_7_days"), {:action => 'query', :date_ranges_filter => "7"}, :title => "7", :class => 'filter_link' %></li>
    <li><%= link_to t(".last_30_days"), {:action => 'query', :date_ranges_filter => "30"}, :title => "30", :class => 'filter_link' %></li>
  </ul>
  <div id="search">
    <%= form_tag "logged_exceptions/query", :id => 'query-form' %>
    <div>
      <%= text_field_tag :query, "", :size => 17 %>
      <%= submit_tag :Find %>
      <%= hidden_field_tag :exception_names_filter %>
      <%= hidden_field_tag :date_ranges_filter %>
      <%= hidden_field_tag :controller_actions_filter %>
      <%= hidden_field_tag :page, (params[:page] || 1) %>
    </div>
    </form>
  </div>
  <%= render :partial => 'feed' %>
</div> <!-- right -->
<div id="left">
  <div class="page" id="showpage" style="display:none;"></div>
  <div class="page">
    <%= render :partial => "exceptions" %>
  </div>
</div>
<div id="activity" style="display:none;">Busy...</div>

app/views/rails_mongo_logger/logged_exceptions/index.js.erb
$('#exceptions').html('<%= escape_javascript render :partial => "exceptions" %>');
$('#showpage').hide();

app/views/rails_mongo_logger/logged_exceptions/query.js.erb
$('#exceptions').html('<%= escape_javascript render :partial => "exceptions" %>');
$('#showpage').hide();

app/views/rails_mongo_logger/logged_exceptions/show.html.erb
<% page_title t(".title") %>
<div id="right">
</div> <!-- right -->
<div id="left">
  <div class="page" id="showpage">
    <%= render :partial => "show" %>
  </div>
</div>

app/views/rails_mongo_logger/logged_exceptions/show.js.erb
$('#showpage').html('<%= escape_javascript render :partial => "show" %>');
$('#showpage').show();